[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --config gunicorn.conf.py wsgi:app"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 20

[env]
PYTHON_VERSION = "3.10"
FLASK_APP = "wsgi.py"
FLASK_ENV = "production"
GUNICORN_TIMEOUT = "120"
GUNICORN_WORKERS = "1"
GUNICORN_THREADS = "4"
GUNICORN_WORKER_CLASS = "gthread"
GUNICORN_WORKER_TMP_DIR = "/dev/shm"
GUNICORN_LOG_LEVEL = "debug" 
