[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && flask db upgrade"

[deploy]
startCommand = "gunicorn wsgi:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.10"
FLASK_APP = "wsgi.py"
