services:
  # Serviço Web (Aplicação Flask)
  - type: web
    name: almoxarifado-flask
    env: python
    region: oregon # Ou outra região de sua preferência
    plan: free # Plano gratuito do Render
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: almoxarifado-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render gera uma chave secreta segura

  # Banco de Dados PostgreSQL
  - type: pserv
    name: almoxarifado-db
    env: postgres
    region: oregon # Use a mesma região do serviço web
    plan: free # Plano gratuito do Render para DB
    postgresMajorVersion: 14 # Ou a versão desejada
    disk:
      sizeGB: 1 # Mínimo no plano gratuito

